// KeyPath's lesson engine: songs in, judgement out, no UI. Every door (Songs,
// Journey, Challenges, Studio) builds on this; see KEYPATH_TUTOR.md §4.
export { parseSmf, SmfError } from './smf'
export type { SmfFile, SmfNote, SmfTrack, ScoreInfo } from './smf'
export { parseMusicXml, looksLikeXml, MusicXmlError } from './musicxml'
export { unzipScore, isZip, MxlError } from './mxl'
export { parseMscx, MscxError } from './mscx'
export { partsOf, suggestParts, suggestScoreParts, songFromParts, suggestSplit, splitHands, SPLIT_RANGE } from './parts'
export type { Part, SongFromPartsOptions } from './parts'
export { stepsOf, notesFor, barName, barSpan } from './song'
export type { Song, SongNote, Step, Hand, Finger, Practice } from './song'
export { checkRange, transposeSong, KEYBOARD_RANGE, applyFit, fitOptions, fitSong, notesToFit, defaultFit, FEW_OUTSIDE } from './range'
export { easyNotes } from './easy'
export type { RangeCheck, FitMode, FitOption, Fitted } from './range'
export { octaveShift } from './octave'
export { Judge } from './judge'
export type { JudgeEvent, JudgeOptions, JudgeSummary, NoteResult, WrongNote, TimingVerdict } from './judge'
export { buildReport, cueFor } from './feedback'
export type { Report, Highlight, BarToWorkOn, Suggestion, LiveCue } from './feedback'
export { DEFAULT_SETTINGS, TIMING_WINDOW_MS, ON_TIME_MS, MIN_VELOCITY, nextStep } from './settings'
export type { JudgeSettings, OnWrong, Timing, ReportDepth, NextStep } from './settings'
