// ─────────────────────────────────────────────────────────────
// Exercise data. Steps + phase breakdowns are grounded in form
// guidance researched per-movement (StrongFirst, BarBend, Kettlebells
// Workouts, et al.).
//
// `phases` map onto the ported Gemini pose library (hinge · stand ·
// press · squat · plank). Where Gemini drew no matching pose we use
// fewer frames; `flip: true` mirrors a repeated pose so it reads as a
// left/right or alternating rep. `accent` drives the card colour.
// ─────────────────────────────────────────────────────────────

export const ACCENTS = {
  red: '#FF1E1E',
  blue: '#1466FF',
  green: '#00A24A',
  magenta: '#FF2D87',
  orange: '#FF8A00',
  teal: '#0FB5AE',
};

export const exercises = [
  {
    id: 'swing',
    num: 1,
    name: 'Kettlebell Swing',
    tag: 'Back · Glutes · Hamstrings',
    tagline: 'A loaded hinge that floats the bell on hip power — not a front raise in disguise.',
    difficulty: 2,
    accent: ACCENTS.red,
    phases: [
      { pose: 'hinge', label: 'Hinge & load' },
      { pose: 'stand', label: 'Hip snap' },
    ],
    steps: [
      'Stand a forearm’s length behind the bell, feet a touch wider than the hips.',
      'Hinge the hips back and hike the bell high between your thighs like a football snap.',
      'Snap the hips forward hard — drive the floor away and squeeze the glutes.',
      'Let the bell float to chest height; the arms only steer, they never lift.',
      'Catch the float, hinge again, and let it pendulum straight back to reload.',
      'Stay braced ear-to-ankle at the top — a plank that happens to be standing.',
    ],
  },
  {
    id: 'goblet-squat',
    num: 2,
    name: 'Goblet Squat',
    tag: 'Quads · Glutes · Core',
    tagline: 'The bell at your chest is a counterweight — it buys you a taller, deeper squat.',
    difficulty: 1,
    accent: ACCENTS.blue,
    phases: [
      { pose: 'stand', label: 'Tall stance' },
      { pose: 'squat', label: 'Sit deep' },
    ],
    steps: [
      'Cup the bell by the horns at chest height, elbows pointing straight down.',
      'Set the feet shoulder-width or a touch wider, toes turned out slightly.',
      'Break at the hips and knees together, spreading the knees over the toes.',
      'Sink below parallel if your mobility allows — chest stays proud throughout.',
      'Drive through the whole foot to stand; squeeze the glutes at the top.',
      'Keep the bell glued to your sternum so it pulls you upright, not forward.',
    ],
  },
  {
    id: 'turkish-get-up',
    num: 3,
    name: 'Turkish Get-Up',
    tag: 'Shoulders · Core · Everything',
    tagline: 'Half-yoga, half-strongman: stand up from the floor without ever lowering the bell.',
    difficulty: 3,
    accent: ACCENTS.orange,
    phases: [
      { pose: 'plank', label: 'Press off the floor' },
      { pose: 'press', label: 'Stand & lock' },
    ],
    steps: [
      'Lie down, press the bell to a locked elbow, eyes fixed on it the whole time.',
      'Same-side knee bent, roll to your free elbow, then post up onto that hand.',
      'Drive the planted foot and hand to bridge the hips high off the floor.',
      'Sweep the straight leg under into a half-kneeling lunge, torso vertical.',
      'Stand straight up, the bell still locked overhead and stacked over the shoulder.',
      'Reverse every step in order back to the floor — same control, same patience.',
    ],
  },
  {
    id: 'single-arm-row',
    num: 4,
    name: 'Single-Arm Row',
    tag: 'Lats · Rhomboids · Biceps',
    tagline: 'Pull with a quiet torso — the bell moves, your hips and spine do not.',
    difficulty: 1,
    accent: ACCENTS.green,
    phases: [
      { pose: 'hinge', label: 'Long hang' },
      { pose: 'stand', label: 'Pull high' },
    ],
    steps: [
      'Stagger your stance or brace a hand on a bench, back flat and parallel to the floor.',
      'Let the working arm hang straight down, shoulder reaching toward the bell.',
      'Brace the core hard — no rotating, no twisting, no hip wiggle to cheat it up.',
      'Drive the elbow up and back toward the hip, like starting a chainsaw.',
      'Squeeze the shoulder blade in at the top and hold for a beat.',
      'Lower under control to a full stretch; the slow descent is where it pays off.',
    ],
  },
  {
    id: 'clean-and-press',
    num: 5,
    name: 'Clean & Press',
    tag: 'Shoulders · Traps · Triceps',
    tagline: 'Zip the bell to the rack, then punch it overhead — power downstairs, strength up.',
    difficulty: 3,
    accent: ACCENTS.magenta,
    phases: [
      { pose: 'hinge', label: 'Backswing' },
      { pose: 'stand', label: 'Clean to rack' },
      { pose: 'press', label: 'Press out' },
    ],
    steps: [
      'Hike the bell back on a single-arm swing, elbow brushing the ribs.',
      'Snap the hips and “zip up the jacket,” keeping the elbow glued to your side.',
      'Spear the hand through so the bell rolls softly to the rack — no wrist bang.',
      'From the rack, brace the core and press straight up; ribs down, no leaning back.',
      'Finish with the biceps by the ear and the bell stacked over the shoulder.',
      'Lower to the rack, then guide it back down into the next backswing.',
    ],
  },
  {
    id: 'snatch',
    num: 6,
    name: 'Kettlebell Snatch',
    tag: 'Power · Shoulders · Back',
    tagline: 'Floor to overhead in one breath — the swing’s explosive, ambitious cousin.',
    difficulty: 3,
    accent: ACCENTS.red,
    phases: [
      { pose: 'hinge', label: 'Hike' },
      { pose: 'press', label: 'Punch overhead' },
    ],
    steps: [
      'Start from a one-arm swing — the bell rises on hip drive, never an arm curl.',
      'As it lifts, let the elbow bend and keep the handle skimming close to the body.',
      'Near face height the bell goes weightless — that’s your moment to act.',
      'Punch the hand up through the handle so the bell rolls over, not slaps, the wrist.',
      'Finish locked out: straight wrist, packed shoulder, ribs down, glutes tight.',
      'Guide it back down close, hinge, and flow straight into the next rep.',
    ],
  },
  {
    id: 'windmill',
    num: 7,
    name: 'Windmill',
    tag: 'Obliques · Hips · Shoulders',
    tagline: 'Mobility wearing a strength costume — bend sideways under a bell that never moves.',
    difficulty: 2,
    accent: ACCENTS.teal,
    phases: [
      { pose: 'press', label: 'Press & set' },
      { pose: 'hinge', label: 'Hinge & reach' },
    ],
    steps: [
      'Press the bell overhead and lock the elbow; both feet angle 45° away from it.',
      'Shift the bell-side hip back and out, keeping that arm vertical and eyes on the bell.',
      'Hinge sideways, tracing the free hand down the inside of the front leg.',
      'Keep the loaded arm straight up — aim for one line from floor hand to bell.',
      'Drive the hip back under to stand tall, arm still locked overhead.',
      'Be humble with the weight; this is a mobility lift first, a strength lift second.',
    ],
  },
  {
    id: 'rdl',
    num: 8,
    name: 'Romanian Deadlift',
    tag: 'Hamstrings · Glutes · Lower Back',
    tagline: 'Push the hips to the wall behind you and feel the hamstrings light up.',
    difficulty: 1,
    accent: ACCENTS.blue,
    phases: [
      { pose: 'stand', label: 'Stand tall' },
      { pose: 'hinge', label: 'Hinge down' },
    ],
    steps: [
      'Hold the bell(s) at your thighs, feet hip-width, a soft unlocked bend in the knees.',
      'Push the hips straight back — the move is at the hip, not a bend at the waist.',
      'Let the bell slide down the front of the legs as the torso tips, spine neutral.',
      'Stop at the first real hamstring stretch, around mid-shin — chase tension, not depth.',
      'Drive the hips forward to stand, squeezing the glutes hard at the top.',
      'Control the lowering; owning the descent is the whole point of the lift.',
    ],
  },
  {
    id: 'renegade-row',
    num: 9,
    name: 'Renegade Row',
    tag: 'Back · Core · Shoulders',
    tagline: 'A plank that rows — your abs spend the whole set fighting the twist.',
    difficulty: 3,
    accent: ACCENTS.orange,
    phases: [
      { pose: 'plank', label: 'Row left' },
      { pose: 'plank', label: 'Row right', flip: true },
    ],
    steps: [
      'Get into a plank gripping two bell handles, hands under the shoulders.',
      'Set the feet wide and brace head-to-heels like a single steel beam.',
      'Row one bell to the hip, elbow tracking back, while the core kills the rotation.',
      'Keep the hips dead level — no piking, no twisting toward the working side.',
      'Lower with control and alternate; wider feet make balancing far kinder.',
      'Optional: add a push-up between rows when you’re feeling brave (or foolish).',
    ],
  },
  {
    id: 'halo',
    num: 10,
    name: 'Kettlebell Halo',
    tag: 'Shoulders · Upper Back · Core',
    tagline: 'Orbit the bell tight around your skull and free up cranky shoulders.',
    difficulty: 1,
    accent: ACCENTS.magenta,
    phases: [
      { pose: 'stand', label: 'Around one way' },
      { pose: 'stand', label: 'And back', flip: true },
    ],
    steps: [
      'Hold the bell upside-down by the horns at chest height, elbows tucked in.',
      'Trace it in a tight circle around the head, close to the skull — no lazy orbit.',
      'Keep the neck long and the chin neutral; the bell moves, the head doesn’t.',
      'Brace the core so the ribcage stays stacked — no swaying at the waist.',
      'Finish all the reps one way, then reverse the direction for the same count.',
      'Go light; this is a control and mobility drill, not a max-effort grind.',
    ],
  },
  {
    id: 'figure-8',
    num: 11,
    name: 'Figure-8',
    tag: 'Core · Grip · Coordination',
    tagline: 'Weave the bell through your legs in an endless loop — rhythm beats raw strength.',
    difficulty: 2,
    accent: ACCENTS.green,
    phases: [
      { pose: 'squat', label: 'Pass left' },
      { pose: 'squat', label: 'Pass right', flip: true },
    ],
    steps: [
      'Stand wide in a quarter-squat, hips hinged slightly, chest up and proud.',
      'Pass the bell from the front through the legs, handing it off behind one thigh.',
      'The waiting hand catches it behind the leg and sweeps it back to the front.',
      'Repeat on the other side so the bell traces a smooth, continuous figure-8.',
      'Keep the hips low and the core braced — let the rhythm carry the weight.',
      'Start slow and light; the grip and the coordination give out before the legs.',
    ],
  },
  {
    id: 'farmers-walk',
    num: 12,
    name: "Farmer's Walk",
    tag: 'Grip · Traps · Core · Legs',
    tagline: 'Pick up heavy, stand tall, and walk. Brutally simple, simply brutal.',
    difficulty: 1,
    accent: ACCENTS.teal,
    phases: [
      { pose: 'stand', label: 'Left lead' },
      { pose: 'stand', label: 'Right lead', flip: true },
    ],
    steps: [
      'Stand between two bells, deadlift them up with a flat back and braced core.',
      'Pack the shoulders down and back — tall posture, no shrugging up to the ears.',
      'Walk with short, deliberate steps; no waddling and no leaning side to side.',
      'Crush the handles and keep breathing in a steady, even rhythm.',
      'Cover a set distance or time, then set the bells down with full control.',
      'Simple in concept, savage in execution — this is what raw strength feels like.',
    ],
  },
];
