/**
 * The demo forest. In **app shape** (not Notion page shape), following Fit
 * Check's `models/demoData.ts` convention — this is what `store.ts` serves
 * when no token is set, so the app is fully usable before a single Notion
 * database exists.
 *
 * Dates are computed relative to today rather than hardcoded, so the
 * understory's season-expiry fade always demos correctly regardless of when
 * this is run — including one row deliberately past the default 90-day
 * season, to exercise expiry on first load.
 */

import type { Thing } from './notion'
import type { Source } from './sources'
import type { Locus } from './loci'
import type { Path } from './paths'
import { todayIso } from './understory'

function daysAgo(n: number): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  // Local calendar date, not UTC — see understory.ts's todayIso.
  return todayIso(d)
}

/** The Sources the demo Things above already reference by id. */
export const DEMO_SOURCES: Source[] = [
  {
    id: 'demo-source-meditations',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    kind: 'Book',
    cover: null,
    koboVolumeId: null,
    notes: '',
  },
  {
    id: 'demo-source-aristotle',
    title: 'Nicomachean Ethics',
    author: 'Aristotle',
    kind: 'Book',
    cover: null,
    koboVolumeId: null,
    notes: '',
  },
  {
    id: 'demo-source-conversation',
    title: 'A friend, on a walk',
    author: '',
    kind: 'Conversation',
    cover: null,
    koboVolumeId: null,
    notes: '',
  },
]

/** One already-coined clearing, so the Clearings view isn't empty on first
 *  load (SILVA.md: every view populated by the demo fixtures) — gathers
 *  demo-thing-2 and demo-thing-3 below, both small moments of noticing
 *  someone else. Loci are coined retrospectively, never at capture, so this
 *  is deliberately the only place `lociIds` gets set outside the app itself. */
export const DEMO_LOCI: Locus[] = [
  {
    id: 'demo-locus-small-attentions',
    name: 'Small attentions',
    meaning: 'Moments where noticing someone else, briefly, said more than expected.',
    coined: daysAgo(40),
  },
  {
    id: 'demo-locus-what-outlasts',
    name: 'What outlasts',
    meaning: 'Things that keep circling the question of being remembered, and by whom.',
    coined: daysAgo(15),
  },
]

export const DEMO_THINGS: Thing[] = [
  {
    id: 'demo-thing-1',
    handle: 'You have power over your mind',
    body: 'You have power over your mind — not outside events. Realize this, and you will find strength.',
    kind: 'Passage',
    state: 'Kept',
    sourceId: 'demo-source-meditations',
    locator: 'Book VI',
    encountered: daysAgo(410),
    kept: daysAgo(395),
    note: 'Read this the week everything felt out of control. Still true.',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: 'kobo-demo-1',
    arrived: null,
  },
  {
    id: 'demo-thing-2',
    handle: 'The dog on the tram stop, waiting',
    body: 'A dog sat at the tram stop for twenty minutes, watching every door open and close, waiting for someone who never came.',
    kind: 'Observation',
    state: 'Kept',
    sourceId: null,
    locator: 'overheard on the 32 tram',
    encountered: daysAgo(120),
    kept: daysAgo(110),
    note: '',
    lociIds: ['demo-locus-small-attentions'],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-3',
    handle: '"What would you do if you weren\'t afraid?"',
    body: '"What would you do if you weren\'t afraid?" "Probably the same thing. I\'d just enjoy it more."',
    kind: 'Dialogue',
    state: 'Kept',
    sourceId: 'demo-source-conversation',
    locator: '',
    encountered: daysAgo(60),
    kept: daysAgo(58),
    note: 'A friend said the second line without thinking. It stopped me.',
    lociIds: ['demo-locus-small-attentions'],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-4',
    handle: 'Is a forest still a forest with one tree?',
    body: 'Is a forest still a forest with one tree, or does the word describe the relation between trees rather than the trees themselves?',
    kind: 'Question',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(200),
    kept: daysAgo(180),
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-5',
    handle: 'draft — on keeping a forest instead of a library',
    body: 'A library is organized so you can find what you already know you want. A forest is organized so you can find what you didn\'t know you were looking for. Most of what I\'ve built has been libraries.',
    kind: 'Mine',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(3),
    kept: daysAgo(3),
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-6',
    handle: 'we are what we repeatedly do',
    body: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
    kind: 'Fragment',
    state: 'Understory',
    sourceId: 'demo-source-aristotle',
    locator: '',
    encountered: daysAgo(5),
    kept: null,
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: 'kobo-demo-6',
    arrived: null,
  },
  {
    id: 'demo-thing-7',
    handle: 'the smell of rain on hot pavement has a name',
    body: 'The smell of rain on hot pavement has a name: petrichor. Someone had to notice it enough to name it.',
    kind: null,
    state: 'Understory',
    sourceId: null,
    locator: '',
    encountered: daysAgo(20),
    kept: null,
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-8',
    handle: 'can a memory be homesick for a place that never existed',
    body: 'Can a memory be homesick for a place that never existed — a composite of a dozen kitchens that feels more like home than any one of them was?',
    kind: 'Question',
    state: 'Understory',
    sourceId: null,
    locator: '',
    encountered: daysAgo(85),
    kept: null,
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-9',
    handle: 'a link with no annotation, just the pull of it',
    body: 'A link with no annotation yet — just the pull of it.',
    kind: 'Link',
    state: 'Understory',
    sourceId: null,
    locator: '',
    encountered: daysAgo(95),
    kept: null,
    note: '',
    lociIds: [],
    image: null,
    link: 'https://example.com/an-essay-worth-keeping',
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-10',
    handle: 'They carved their names into the wet cement',
    body: 'They carved their names into the wet cement of a pavement that will be dug up in nine years. Everyone knew. They did it anyway.',
    kind: 'Observation',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(70),
    kept: daysAgo(66),
    note: 'The impermanence was the point, maybe.',
    lociIds: ['demo-locus-what-outlasts'],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-11',
    handle: 'Everything is short-lived, both the rememberer and the remembered',
    body: 'Everything is short-lived, both the one who remembers and the one who is remembered.',
    kind: 'Passage',
    state: 'Kept',
    sourceId: 'demo-source-meditations',
    locator: 'Book IV',
    encountered: daysAgo(300),
    kept: daysAgo(290),
    note: '',
    lociIds: ['demo-locus-what-outlasts'],
    image: null,
    link: null,
    koboBookmarkId: 'kobo-demo-11',
    arrived: null,
  },
  {
    id: 'demo-thing-12',
    handle: 'Who is the last person who will say your name',
    body: 'Who is the last person who will say your name out loud, and how long after you is that?',
    kind: 'Question',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(48),
    kept: daysAgo(45),
    note: '',
    lociIds: ['demo-locus-what-outlasts'],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-13',
    handle: 'A grandmother\'s recipe card, in her handwriting',
    body: 'A recipe card in my grandmother\'s handwriting, with a correction she made to her own measurements. That correction is more of her than the photograph is.',
    kind: 'Mine',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(35),
    kept: daysAgo(33),
    note: 'What survives of a person is mostly their revisions.',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-14',
    handle: 'The tree that falls in a forest nobody has named',
    body: 'A tree falls in a forest nobody has named, and the forest is not diminished by the absence of a witness. Only the account of it is.',
    kind: 'Fragment',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(230),
    kept: daysAgo(225),
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-15',
    handle: 'He kept every ticket stub for forty years',
    body: 'He kept every ticket stub for forty years and never once looked at them. The keeping was the whole activity.',
    kind: 'Observation',
    state: 'Kept',
    sourceId: 'demo-source-conversation',
    locator: '',
    encountered: daysAgo(95),
    kept: daysAgo(90),
    note: 'Uncomfortably close to what I am doing here.',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
  {
    id: 'demo-thing-16',
    handle: 'The only real failure is to be forgotten by yourself',
    body: 'The only real failure is being forgotten by yourself — waking up one day unable to account for what you used to care about.',
    kind: 'Passage',
    state: 'Kept',
    sourceId: null,
    locator: '',
    encountered: daysAgo(150),
    kept: daysAgo(145),
    note: '',
    lociIds: [],
    image: null,
    link: null,
    koboBookmarkId: null,
    arrived: null,
  },
]

/** Two already-made paths, so Underground isn't empty on first load —
 *  one drawn unprompted (`origin: 'Yours'`) and one that came out of accepting
 *  a provocation (`origin: 'Accepted'`), so the Underground's origin badge —
 *  descriptive only, never scored — has both states to show on first run. */
export const DEMO_PATHS: Path[] = [
  {
    id: 'demo-path-1',
    label: 'You have power over your mind → draft — on keeping a forest instead of a library',
    fromId: 'demo-thing-1',
    toId: 'demo-thing-5',
    why: 'Both are about where the self actually has control — over judgment and tending, not over what grows or what happens.',
    made: daysAgo(2),
    origin: 'Yours',
  },
  {
    id: 'demo-path-2',
    label: 'He kept every ticket stub for forty years → Who is the last person who will say your name',
    fromId: 'demo-thing-15',
    toId: 'demo-thing-12',
    why: 'Both are about keeping as an act aimed at nobody in particular — the stubs were never for looking at, and the name is never for the person it belongs to.',
    made: daysAgo(9),
    origin: 'Accepted',
  },
]
